<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LinkLogistics.Shared\LinkLogistics.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>LinkLogistics.Core</RootNamespace>
  </PropertyGroup>

</Project>
