<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>LinkLogistics.Web</RootNamespace>
    <UserSecretsId>linklogistics-web</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkLogistics.Core\LinkLogistics.Core.csproj" />
    <ProjectReference Include="..\LinkLogistics.Shared\LinkLogistics.Shared.csproj" />
  </ItemGroup>

</Project>
